export const palabras = [
  "CAFETERA", "SILLA", "RELOJ", "ESPEJO", "ALMOHADA", 
  "LLAVES", "COMPUTADORA", "LIBRO", "ZAPATOS", "BICICLETA", 
  "MESA", "LAMPARA", "TELEVISOR", "TELEFONO", "VENTANA", 
  "PUERTA", "BOLSA", "ESCOBA", "MOCHILA", "POROTO", 
  "SOMBRERO", "CUADRO", "PLATO", "CUCHILLO", "TENEDOR", 
  "CUCHARA", "REMERA", "PANTALON", "ALBAÑIL", "NARANJA"
];